### ISSUE TITLE
Error: Cannot find module '../scribe'  

### ISSUE THREAD

**Issue by imeninnik** [bluejamesbond/Scribe.js#59]
Try to make everything by your instruction
npm install and then copy simple express example

```
E:\***\src>node server
module.js:338
    throw err;
          ^
Error: Cannot find module '../scribe'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at E:\node.js\#Diatom\spin.3\src\server.js:5:18
    at Object.<anonymous> (E:\node.js\#Diatom\spin.3\src\server.js:19:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by guillaumewuip** [comment]
Examples are intended to be run after a `git clone` of the repo.
Simply change `scribe = require('../scribe')()` with `scribe = require('scribe')()`

**Comment by imeninnik** [comment]
Thanks for answer and sorry, but that also does not helps. 
I've tried with
`var scribe = require('../scribe')();` and `var scribe = require('scribe')();` as well. 

Just to clearify: any other modules I usee in app (like epress, fs, bodyParse, unirest etc) are works as expected

**Comment by guillaumewuip** [comment]
Ok this is strange. As other modules work as expected I don't understand why it's buggy here.
What is your new error message ?

**Comment by dhiraj-cd** [comment]
is it working? I am getting same error? may be some silly mistake but I have tried all of the above options.
used npm install with and w/out "-g"

**Comment by mbuckbee** [comment]
This is quite late, but as a someone else new to node+express+scribe, the necessary change was to 

`require('scribe-js')()`

**Comment by alexandrecardinal** [comment]
@mbuckbee That did it for me, thanks!
