### ISSUE TITLE
Syntax error "Unexpected end of input"

### ISSUE THREAD

**Issue by sam2x** [bluejamesbond/Scribe.js#72]
When my app close unexpectedly (eg: server crash), i got the following error : 

     [path]/node_modules/scribe-js/lib/logWriter.js:83
                        throw e;
                              ^
     SyntaxError: Unexpected end of input
         at Object.parse (native)
         at /home/[path]/node_modules/scribe-js/lib/logWriter.js:81:45
         at fs.js:272:14
         at Object.oncomplete (fs.js:108:15)

To "fix" the problem i have to remove logs/history.json which is really meaningless. Any solution please ? 
This error seems similar to #65

**Comment by Thatkookooguy** [comment]
That's because you're running (or ran) your server with `sudo`. So one of the times when your `logs/` directory got created, your normal user didn't have permission to write to that folder.

try going into the folder were your `log/` folder is, and run `sudo chmod -R 777 ./logs/` (or whatever your logs folder is called :smile: ).

everything should work now

**Comment by sam2x** [comment]
Thanks i'll try!

**Comment by bluejamesbond** [comment]
Be sure checkout the alpha release. It might provide you a between solution

**Comment by mrPalomar** [comment]
This can also happen if the history.json file is empty, which seems to happen to me a lot during app development.
